{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chronos-todo.fullname" . }}-backend
  labels:
    {{- include "chronos-todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: 8000
    protocol: TCP
  selector:
    {{- include "chronos-todo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
