{{- if .Values.dapr.enabled -}}
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: chronos-dapr-config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"
  metrics:
    enabled: true
  logs:
    level: {{ .Values.backend.dapr.logLevel | default "info" }}
{{- end }}
