{{- if and .Values.dapr.enabled .Values.redpanda.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: {{ include "chronos-todo.fullname" . }}-redpanda:9092
  - name: consumerGroup
    value: chronos-service
  - name: authRequired
    value: "false"
  - name: initialOffset
    value: "newest"
{{- end }}
